=== First Rocket Build
.Disciplines:
* Rocketry
* Physics
* Hobby safety

.Preparation:
Distribute rocket build instructions for the rockets the students
will be building to the assistants ahead of time.

.Resources:
* Dowloadable Estes Rocket Instructions:
** https://www.estesrockets.com/customer-service/instructions
* Finding center of gravity on a ruler
** https://www.youtube.com/watch?v=djmec-Bweeg

.Materials:
* Beginners rocket kits
* Hobby knifes
* Wood/Plastic Glues
* Safety Glasses
* Ruler or long tube
* Binder clips or clothespins

.Location:
Classroom/Lab

==== Lecture

===== Center of Gravity (CG)

* Does anyone know what center of gravity is?
* Demonstrate sliding fingers together on ruler or long tube
  to find center of gravity in the middle.
* Attach clip to one end and show how CG moved toward that end.
* Attach many more clips and show how much CG moves.
* Attach clip to opposite and and show how it starts moving back to
  the center.
* Equate the ruler or tube with the rocket body. If a force is applied
  to either side, where will the pivot point be? (the rocket pivots about
  the CG)

* What happens to the center of gravity as the engine burns its fuel?
  (back of the rocket gets lighter, CG moves forward - as an example,
  take away clips from the end of the ruler/tube).

===== Center of Pressure (CP)

* Center of pressure is like the center of gravity, but instead of using
  the mass of the rocket, it uses the surface area of the rocket.
  It is the point on the rocket you can consider all of the aerodynamic
  force to be concentrated.
** Recall the parachute experiment and how air exerted a force to slow
   the descent.
* Demonstrate how the rocket will move if the CP is in front of or
  behind the CG.
* Ideally a stable rocket should have its CP 1-2 body tube diameters
  behind the CG. The CP always wants to follow the wind. Which
  way is the wind for a zooming rocket? (downward, so as the rocket
  flies upward the CP wants to follow the wind and if the rocket starts to
  veer off, the force at the CP will straighten it out).
* An unstable rocket has the CP in front of the CG. Demonstrate with a
  rocket. What will happen if there is a force in front of the CG
  constantly trying to follow the wind? (Demonstrate that as the rocket
  turns, the direction of the wind turns so the CP trys to follow and
  turns the rocket and so forth and the rocket loops dangerously close
  to the ground)
* A marginally stable rocket will have its CP very close to the CG.
  Air pressure forces will cause very large movements... demonstrate
  how a small movement close to the CG fulcrum displaces the rocket much
  more than the same amount of movement far away.
  How do you think it will fly? (Erratic, possibly spiraling. May stabilize
  as the rocket fuel burns because the CG will move forward away from
  the CP).
* An overstable rocket has its CP too far behind the CG. How
  will it fly? (turns into even the slightest breeze
  and shoots horizontally across the field).
* Find center or pressure by cutting out profile of rocket in cardboard and
  finding where the center of gravity of the cardboard cutout is. This point
  will be the center of pressure of the rocket.
** Cardboard cutout "converts" surface area to mass so then the location
   of the CM of the cutout represents the CP of the rocket.
** How can we move the CP back? (bigger fins; also adds mass and moves the
   CG backward a little bit too)
** How can we move the CG forward? (weight in the nosecone)
** Rocket needs to be stable with both an unused and a spent rocket engine.
   Why? (As the rocket fuel burns, the tail of the rocket will get lighter,
   and which way does that move the CG? Forward while the CP stays in
   the same place... Rocket may go straight up, become over-stable and veer
   in to the wind).
* Swing test. Tie a string around rocket at CG and spin it around.
  A stable rocket should fly true. Unstable will fly backwards. Marginally
  stable will tumble.

===== Hobby Building
There's no "spare parts" for your rocket kit.
Work slowly and carefully. Any mistake will have to be repaired.

Plastic glues. Try to avoid breathing in the fumes.
If it gets on your hands, immediately go wash.
Never touch your face, mouth or eyes after handling the glue.
Be sure to wash up after done using the glue.

Knife safety covered in last class. Adult helpers will manage the hobby
knife at each table.

Drawing a straight line up and down a tube.

Drawing a straight line around a tube.


.Teaming:
Teams of 2-3 grouping younger and older student(s) together

.Challenge:
Placeholder

.Class Inquiry:
Placeholder

.Further Challenges:
Placeholder

// vim: set syntax=asciidoc:
