=== Ballistic Pumpkins
.Disciplines:
- Mechanical Engineering

.Setup:
Can either have teams build multiple trebs or build one trebuchet (let
the whole class assemble it as 1 team) and then let them break out and
compete on getting the best distance with their own customized sling designs.

Miniature pumpkin gourds or alternatively golf balls may be used for
launching. You could get orange golf balls and or decorate them like
jack-o-lanterns to keep with the pumpkin theme.

.Resources:
- https://www.punkinchunkin.com/
- http://www.sciencechannel.com/tv-shows/punkin-chunkin/
- https://www.youtube.com/watch?v=dmSyrGsqmg8
- http://www.real-world-physics-problems.com/trebuchet-physics.html
- MythBusters:
  * https://www.youtube.com/watch?v=9-Hwxw4fgqk
  * https://www.youtube.com/watch?v=9-Hwxw4fgqk
- http://www.instructables.com/id/Trebuchet-Project/

.Materials:
- Garbage bags for cleanup
- TODO: slingshot/trebuchet building materials
- Minature pumpkins/gourds
- Golf balls
- ≥100ft long tape measure
- Lawn Marking chalk
- Online media access

.Location:
Large field outside.

.Preparation:
- Measure out 10ft increments in the field and mark with chalk

.Demonstration:
Show Punkin Chunkin documentary:
https://www.youtube.com/watch?v=dmSyrGsqmg8

Show discovery channel video:
http://www.sciencechannel.com/tv-shows/punkin-chunkin/

.Class Inquiry:

.Teaming:
Teams of 2-3 making sure youngest are teamed with older student(s)

.Challenge:
"Launch a mini-pumpkin as far as possible"

.Class Inquiry:

.Further Challenges:
"Launch a mini-pumpkin into a target bucket"

// vim: set syntax=asciidoc:

