=== Delicious Engineering
.Disciplines:
* Math

.Resources:
* http://www.evilmadscientist.com/2013/sconic-sections/
* Vi Hart Cookie Shapes: https://www.youtube.com/watch?v=_n1126GoxbU
* Vi Hart Fruit by the Foot:  https://www.youtube.com/watch?v=Am-a5x9DGjg

.Materials:
* TODO: Adjust quantities
* Cone shaped paper cups
* 4 cups flour
* 1/3 cup sugar
* 4 1/2 teaspons baking powder
* 2 eggs, beaten
* 3/4 stick of butter, softened
* 1 cup milk

WARNING: Identify any food allergies and accommodate appropriately

.Location:
Start in classroom and move to kitchen facilities.

.Preparation:
Write the challenge on the board.

Consider making the dough ahead of time so the class can form it
and bake it more quickly.

.Class Inquiry:
Ask the class to come up with ideas for making edible things
related to engineering.

IMPORTANT: Discuss kitchen safety and cleanliness

.Demonstration:

.Class Inquiry:
Show the Vi Hart Cookie Shapes video:
https://www.youtube.com/watch?v=_n1126GoxbU

Fruit by the foot:
https://www.youtube.com/watch?v=Am-a5x9DGjg

.Teaming:
Whole class activity

.Challenge:
"Make engineering delicious"

.Class Inquiry:

.Further Challenges:

// vim: set syntax=asciidoc:

