=== Paddle Power
.Disciplines:
* Naval Engineering
* Mechanical Engineering

.Setup:

.Resources:
* http://www-tc.pbskids.org/designsquad/pdf/parentseducators/DS_Act_Guide_complete.pdf
* http://pbskids.org/designsquad/build/paddle-power/
* Design Squad Season 2, Episode 8: Aquatic Robots

.Materials:
* Large tub or large watertight storage bin
* Stopwatch
* Internet Media Access
* Per team:
** Chipboard cardboard (such as a cereal box)
** Plastic tape
** 2 paper cups (≥8oz)
** Plastic wrap
** 5 rubber bands
** Scissors
** Straws
** Washers
** Dowels

.Location:
Inside or outside on a warm day

.Preparation:
Fill the tub with water.

.Demonstration:
Watch the Design Squad video when done.
http://pbskids.org/designsquad/build/paddle-power/

Loop a 1x2" piece of cardboard through a rubber band hold taught between
your fingers. Illustrate winding it up and letting it go to show how it spins.

Introduce potential (wound up rubber band) and kinetic energy (unwinding
rubber band and spinning paddle).

.Class Inquiry:
* Where is the energy stored?
* How can the potential energy be increased?
* How can you tell when potential energy is being used?
* What are the different kinds of kinetic energy that occurs as the boat moves
  through the water?
* What other examples of potential and kinetic energy can you think of?

.Teaming:
Teams of 2-3. Partnering younger with older students.

.Challenge:
Build a boat that paddles itself using a rubber band as its power source.

Time how long it takes for the boat to travel across the tub. Have students
keep records in their engineeering notebooks.

// vim: set syntax=asciidoc:
