=== Spooky Engineering
.Disciplines:
* Chemical Engineering

.Setup:

.Resources:
* http://www.weareteachers.com/blogs/post/2013/09/17/spooky-science-ideas
* http://www.science-sparks.com/2012/09/20/spooky-lava-lamps/
* http://www.weareteachers.com/lessons-resources/details/diy-slime
* http://www.instructables.com/id/Oobleck/
* https://en.wikipedia.org/wiki/Non-Newtonian_fluid
* Vi Hart Scary Sierpinski Skull: https://www.youtube.com/watch?v=z8ZWlUamNPI

.Materials:

* Food coloring
* Alka-seltzer
* Vegetable oil
* Dish soap

Per student:

* A clear plastic bottle or jar
* A bottle of vegetable oil
* Cup of water
* Dixie cup of corn starch
* Paper bowl
* Spoon

.Location:
Classroom/Lab

.Preparation:

WARNING: Collect all of the bottle/jar tops before beginning the activity. The
students won't be able to resist capping their lava lamps after putting in the
alka-seltzer which will cause pressure build up and potential explosion.  You
could also make a safety demonstration by putting water and alka-seltzer into a
capped bottle made of lightweight plastic and then leaving it in a safe
location where it can explode without injuring anyone (safety glasses
recommended).

.Demonstration:

.Class Inquiry:
.Teaming:
Individual or teams based on amount of supplies available.

.Challenge:
Perform some spooky Mad Scientist Experiments.

"Make a Lava Lamp from varying density liquids"

"Make Oobleck: a Non Newtonian Fluid"

Standard lava lamp:
* Fill the bottle or jar a quarter full with water and fill the rest with vegetable oil.
* After the separation between the oil and water settles add several drops of food coloring.
* Add half an alka seltzer for a bubbling reaction.
* Add more bits of alka-seltzer to create a lava-lamp rising and falling of bubbles.

Let the kids design their own lava lamp using dish soap, water, vegetable oil and food coloring.
Things to experiment with include:
* Order in which liquids are added
* Size of alka-seltzer tablets
* When to add food coloring


.Class Inquiry:
TODO: Education on reaction of alka-seltzer
Discussion on density. Ask about why the oil and water separate. Can the
class think of different density gasses?

.Oobleck
Non Newtonian fluid

Mix 1 cup water with 1.5-2cups corn starch (about 1:2 ratio water to cornstarch)
and a few drops of food coloring
in mixing bowl. Student's will have a Non Newtonian Fluid which acts like
a liquid when poured but as a solid when touched.

* If the oobleck is too watery add a spoon of cornstarch and mix in thoroughly
* If it isn't watery when picked up, add a spoon of water
* Repeat until achieving proper consistency



.Class Inquiry
Unlike most fluids, a non-Newtonian fluid's viscosity is dependent on
the shear rate it is exposed to. Silly Putty is another example.
It will stretch and mold, but ball it up and throw it and it bounces.

.Further Challenges:
Prepare for a Ballistic Pumpkin challenge for the next meeting after Halloween.
Have students bring in small pumpkins/Jack-O-Lanterns that may be launched
across the field outside. Brainstorm some ideas for launching pumpkins.  Watch
some videos on Trebuchets and Punkin Chunkin.

// vim: set syntax=asciidoc:

