=== Water Bottle Flip Optimization
.Disciplines:
* Dynamics
* Data Analysis

.Setup:

.Resources:
* dy/dan BottleFlipping and the Lessons you throw back
** http://blog.mrmeyer.com/2016/bottleflipping-the-lessons-you-throw-back/
** https://s3.amazonaws.com/ddmeyer/bottle-flipping-media.zip
* Desmos water bottle flipping calculator
** https://www.desmos.com/calculator/k54pcfbuy4
* link:https://en.wikipedia.org/wiki/Dynamics_(mechanics)[https://en.wikipedia.org/wiki/Dynamics_(mechanics)]

.Materials:
* 16-20 ounce water bottle per student
* Digital scale
* Measuring cups
* Water

.Location:
Cafeteria or large room with tables.

.Preparation:
Distribute data sheets for every participant.

.Class Inquiry:
Ask the class for ideas for the meaning of "Dynamics".

[quote, Wikipedia, Engineering]
_______________________________

Dynamics is a branch of applied mathematics (specifically classical mechanics)
concerned with the study of forces and torques and their effect on motion.
_______________________________

In other words, how something moves when acted on by forces.

.Demonstration:
Show the Desmos water bottle flipping calculator. Inquire of the class
what they think it is demonstrating. Play with the various controls to
change the motion. Point out the paths trace by the top and bottom of the
model.

Show the Act 1 video from dy/dan's bottle flipping media. Ask the class to
predict which of A,B,C,D trials will land standing.

Show the Act 2 video and pause on each trial. See if using the graph overlay
will help the predictions.

Show the Act 3 video for the results.


.Teaming:
Individual

.Challenge:
Find the optimum amount of water for successful bottle flipping.

With each trial, suggest that students empty their bottle and refill
it with the volume of water under test. Otherwise, incrementally
adding/subtracting water will introduce errors to the recorded amount
of water. Alternatively, water may be incrementally added/subtracted if
the digital scale will be used to measure the weight before each trial.

Fluid ounces is volume and ounces is weight, but for water, the two
quantities are equal.

.Class Inquiry:
Enter the student recorded data into the flip_results spreadsheet and
import it into the Jupyter notebook for analysis.

Explain a histogram.  Show how the results indicate which quantity of water
resulted in the highest frequency of good flip percentages.

Also show histograms for raw number of good flips and total flips.
Are the results any different?

Move on to binning by student name.
Show results for percentages, good flips and total flips.

Give an example where someone had 10 good flips in a row with no bad flips
and someone else had 10 good flips and 10 bad flips. They both have the
same number of good flips, but which was better? 100% vs. 50%.

.Further Challenges:
After finding the optimum amount of water, have everyone fill there bottle
with their ideal amount. Line everyone up and see if you can get the whole
class to successively (or simultaneously) flip their bottles and land
upright.

// vim: set syntax=asciidoc:
