=== What is Engineering?

.Disciplines:
* Engineering Fundamentals

.Resources:
* What's an Engineer? Crash Course Kids
** https://www.youtube.com/watch?v=owHF9iLyxic
* Engineering Process
** https://www.youtube.com/watch?v=fxJWin195kU

.Philosophy:
For this and all ensuing workshops, prioritize allowing the students to steer the direction.
These workshops are guidelines for providing a medium for exploration but there's no need to hold fast to them.
If the class is motivated to do something totally different, encourage this even if it's not part of the plan.

For reference, Wikipedia defines Engineering as follows, (there's no need to actually read this to the class, but it may be helpful in case you get a few pedantic inquires):

[quote, Wikipedia, Engineering]
_______________________________
Engineering is the application of mathematics, empirical evidence and
scientific, economic, social, and practical knowledge in order to invent,
innovate, design, build, maintain, research, and improve structures, machines,
tools, systems, components, materials, processes and organizations.

The discipline of engineering is extremely broad, and encompasses a range of
more specialized fields of engineering, each with a more specific emphasis on
particular areas of applied science, technology and types of application.

The term Engineering is derived from the Latin ingenium, meaning "cleverness"
and ingeniare, meaning "to contrive, devise".
_______________________________

In short: Engineering is the application of knowledge to invent, design and
build systems.

.Resources:
* http://www-tc.pbskids.org/designsquad/pdf/parentseducators/DS_Act_Guide_complete.pdf
* http://www.mechatronics-mec.org/downloads/Engineering%20Notebook08.pdf

.Materials:
* Large whiteboard and dry erase markers
* Tape (e.g. masking tape that will be easily removable from whiteboard)
* Index cards
* Computer workstation with internet access
* Make Magazines and/or similar
* Various gears and other engineering like gizmos
* Ruler
* Various stickers and coloring sheets of technical items for students
  to choose for personalizing their engineering notebooks. Example
  coloring sheet ideas:
** Gears, pulleys, clocks, Rube Goldberg
** Vehicles: automotive, nautical, construction equipment, aerospace
** Instrumentation
** Computers
** Drafting symbols/stickers

.Location:
Indoor classroom/lab environment

.Preparation:
Write the challenge "What is engineering?" on the board.

Draw five large circles on the board. At the top of each circle write each of
the following categories:

* Mechanical
* Chemical
* Civil
* Electrical
* Software
* Interdisciplinary

For reference here are some definitions:

[quote, Wikipedia, List of engineering branches]
_______________________________

Mechanical engineering:: is the discipline that applies the principles of engineering, physics, and materials science for the design, analysis, manufacturing, and maintenance of mechanical systems. It is the branch of engineering that involves the design, production, and operation of machinery. It is one of the oldest and broadest of the engineering disciplines.

Chemical engineering:: is a branch of engineering that applies physical sciences (physics and chemistry) and life sciences (microbiology and biochemistry) together with applied mathematics and economics to produce, transform, transport, and properly use chemicals, materials and energy. Essentially, chemical engineers design large-scale processes that convert chemicals, raw materials, living cells, microorganisms and energy into useful forms and products.

Civil engineering:: is a professional engineering discipline that deals with the design, construction, and maintenance of the physical and naturally built environment, including works like roads, bridges, canals, dams, and buildings.

Electrical engineering:: comprises the study and application of electricity,
electronics, and electromagnetism.

Software engineering:: is the application of engineering to the design, development, implementation and maintenance of software in a systematic method.
_______________________________

Wikipedia classifies the sub-disciplines as follows:

* Civil
** Architectural, Construction, Earthquake, Hydraulic, Mining, Structural,
   Geotechnical, Transportation, Environmental
* Mechanical
** Aerospace, Acoustical, Automotive, Marine, Mechatronics, Railway
* Electrical
** Computer, Control, Electronics, Electromechanics, Optical, Power,
   Photonics, Telecommunications, Radio Frequency
* Chemical
** Biochemical, Biological, Molecular, Nanotechnology, Process, Reaction,
   Thermodynamics, Transport phenomena
* Interdisciplinary
** Audio, Engineering mathematics, Biomedical, Fire, Industrial,
   Materials science, Robotics, Military, Nuclear, Security, Systems, Privacy


Distribute the gears/gizmos, magazines and index cards across all the classroom
tables.  Don't offer direction one way or another whether the kids are allowed
to touch these things. When they do start playing/reading don't make them stop
when you move on to new activities.

Have a computer workstation set up and pointing at the webpage: http://spacefem.com/quizzes/engineer .
During the challenge allow students to individually come up and take the quiz (with assistance if necessary).
If you have engineering notebooks, have them log their results.

Consider starting the meeting seated among the students: "So, who's going to teach us today?".
If there are any volunteers, see where it goes before taking formal charge.

[NOTE]
.Engineering Notebook (Optional)
========================
Have the students assemble an Engineering Notebook. Notify club members before
this first meeting to bring the necessary notebook supplies.  They can use a
notebook of their own choice suitable to their tastes (spiral bound,
composition, binder, pocket folder with brads, etc.). Absent any strong student
preference though, suggest a 1" 3 ring binder with 3-hole filler graph or
engineering pad paper.  This way paper can be used for scratch work as
necessary while archival worthy pages can be placed in the binder.
Encourage doodling in their notebooks

A good engineering notebook is a valuable tool to a practicing engineer
but assigning too much importance to it here may be of minimal value.
Especially if it gets in the way of the creative process. It may be better to
instead have a class notebook/binder that students can take turns writing in or
that students can submit reports to.
========================

.Challenge:
Pose the question "What is engineering?".
Allow the discussion to be driven by the students.
Invite the students to write down or draw something on the index cards that they think has to do with engineering.
Let them make as many index cards as they want.

Also create cards (optionally extra large) with your own selection of engineering disciplines.
My choices include: Acoustical, Aerospace, Architectural, Automotive, Biomedical, Chemical, Civil, Computer Aided, Electrical, Manufacturing, Marine, Mechanical, Optical, Robotic, Software.

Have the students tape their cards into as many of the 5 category circles drawn up on the board.
For example an Automotive engineering card might well be placed in each of the circles whereas the gears would likely only be placed in the Mechanical circle.

Based on the results illustrate some Venn diagrams for various disciplines.
Ask the students to pick some of their favorite cards and try to identify a discipline that they like.

.Optional notebook activity
Have the students log their favorite discipline in their notebook and compare that to their quiz results.
Have them put their name and date on the page.

Redistribute the notebooks so everyone has somebody else's notebook.
Invite the students to report on whose notebook they got and what kind of engineer their colleague is.
As a "peer review" then they can sign and date their name at the bottom of the page and return the notebook to the owner.

==== Additional activities

Optionally bring the <<straw_rocket>> materials as an additional activity for students.

Make worksheets that the students can populate Venn diagrams themselves.
Make 1" - 1.5" diameter circular icon images on a printed page that can be punched out with a 1" - 1.5" punch.
Each image can be an engineering related picture/term.
The graphics can be line art and the students can be encouraged to color them as they please.

* Gears: mechanical, automotive
* Computer workstation: software and all disciplines
* Iconic lab glassware: chemical
* Optics, Laser: optical
* Rocket, airplane: aerospace
* Heart: biomedical
* Eyeball: biomedical optics
* Boat, Dam: Marine, mechanical
* Robot: electrical, software robotic
* Assembly line: manufacturing
* Bridge: civil, mechanical, architectural
* Computer chip: electrical
* skyscraper building: architectural, mechanical
* electrical symbols: resistor, capacitor, power supply, opamp etc
* drafting symbols: centerline, dimensional callout etc
* Also have some blank disks for the kids to draw their own pictures/terms

// vim: set syntax=asciidoc:
